@extends('layouts.pdf')

@section('content')
    <div style="margin-bottom: 20px;">
        <h3 style="text-align: center; text-transform: uppercase; margin-bottom: 5px;">Appointments Report</h3>
        <div style="text-align: center; font-size: 11px; color: #64748b;">
            <strong>Generated:</strong> {{ now()->format('M d, Y, h:i A') }}
            @if(isset($start) && isset($end))
                | <strong>Period:</strong> {{ $start }} to {{ $end }}
            @endif
            | <strong>Total:</strong> {{ count($appointments) }}
        </div>
    </div>

    <table style="width: 100%; border-collapse: collapse;">
        <thead>
            <tr>
                <th style="width: 5%; text-align: center;">#</th>
                <th style="width: 20%;">Title</th>
                <th style="width: 25%;">Description</th>
                <th style="width: 12%;">Customer</th>
                <th style="width: 12%;">Employee</th>
                <th style="width: 14%;">Scheduled At</th>
                <th style="width: 12%; text-align: center;">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($appointments as $index => $appointment)
                <tr>
                    <td style="text-align: center;">{{ $index + 1 }}</td>
                    <td>{{ $appointment->title }}</td>
                    <td>{{ Str::limit($appointment->description ?? '-', 40) }}</td>
                    <td>{{ $appointment->user ? $appointment->user->name : '-' }}</td>
                    <td>{{ $appointment->employee ? $appointment->employee->name : 'Unassigned' }}</td>
                    <td>{{ \Carbon\Carbon::parse($appointment->scheduled_at)->format('Y-m-d H:i') }}</td>
                    <td style="text-align: center;">
                        <span
                            style="text-transform: capitalize; padding: 2px 4px; border-radius: 4px; background: {{ $appointment->status == 'completed' ? '#dcfce7' : ($appointment->status == 'scheduled' ? '#e0e7ff' : '#f1f5f9') }}; font-size: 10px;">
                            {{ ucfirst($appointment->status) }}
                        </span>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align:center; padding: 20px;">No appointments found for this report.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <table class="bottom-container">
        <tr>
            <td style="width: 50%;">
                <div class="signature-box">
                    <div style="font-size: 10px; color: #94a3b8; margin-bottom: 5px;">GENERATED BY</div>
                    <div class="signature-name">{{ auth()->user()->name ?? 'System Admin' }}</div>
                    <div class="signature-role">{{ auth()->user()->role ?? 'Administrator' }}</div>
                    <div class="signature-line"></div>
                    <div style="font-size: 9px; color: #94a3b8;">Signature & Date</div>
                </div>
            </td>
            <td style="width: 50%;">
                <div class="summary-box" style="width: 100%; margin-top: 0;">
                    <div class="summary-row"
                        style="background: #f8fafc; border-bottom: 1px solid #e2e8f0; font-weight: bold; text-align: center;">
                        APPOINTMENT SUMMARY</div>
                    <div class="summary-row">
                        <span class="summary-label">Total Appointments:</span>
                        <span class="summary-val">{{ count($appointments) }}</span>
                    </div>
                    <div class="summary-row">
                        <span class="summary-label">Completed:</span>
                        <span class="summary-val">{{ $appointments->where('status', 'completed')->count() }}</span>
                    </div>
                    <div class="summary-row">
                        <span class="summary-label">Scheduled:</span>
                        <span class="summary-val">{{ $appointments->where('status', 'scheduled')->count() }}</span>
                    </div>
                </div>
            </td>
        </tr>
    </table>
@endsection