@extends('layouts.pdf')

@section('content')
    <div style="margin-bottom: 20px;">
        <h3 style="text-align: center; text-transform: uppercase; margin-bottom: 5px;">Stock In Report (Manager)</h3>
        <div style="text-align: center; font-size: 11px; color: #64748b;">
            <strong>Generated:</strong> {{ now()->format('M d, Y, h:i A') }}
        </div>
    </div>

    <table style="width: 100%; border-collapse: collapse;">
        <thead>
            <tr>
                <th style="width: 5%; text-align: center;">#</th>
                <th style="width: 20%;">Product</th>
                <th style="width: 20%;">Supplier</th>
                <th style="width: 10%; text-align: center;">Size/Qty</th>
                <th style="width: 15%; text-align: right;">Unit Cost</th>
                <th style="width: 15%; text-align: right;">Total Cost</th>
                <th style="width: 15%;">Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($stockIns as $stock)
                <tr>
                    <td style="text-align: center;">{{ $loop->iteration }}</td>
                    <td>{{ $stock->product->name ?? 'Deleted' }}</td>
                    <td>{{ $stock->supplier->name ?? 'N/A' }}</td>
                    <td style="text-align: center;">{{ $stock->quantity }}</td>
                    <td style="text-align: right;">{{ number_format($stock->unit_cost, 2) }}</td>
                    <td style="text-align: right;">{{ number_format($stock->total_cost, 2) }}</td>
                    <td>{{ $stock->stock_in_date->format('Y-m-d') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align:center; padding: 20px;">No stock entries found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <table class="bottom-container">
        <tr>
            <td style="width: 50%;">
                <div class="signature-box">
                    <div style="font-size: 10px; color: #94a3b8; margin-bottom: 5px;">GENERATED BY</div>
                    <div class="signature-name">{{ auth()->user()->name ?? 'System Manager' }}</div>
                    <div class="signature-role">{{ auth()->user()->role ?? 'Manager' }}</div>
                    <div class="signature-line"></div>
                    <div style="font-size: 9px; color: #94a3b8;">Signature & Date</div>
                </div>
            </td>
            <td style="width: 50%;">
                <div class="summary-box" style="width: 100%; margin-top: 0;">
                    <div class="summary-row"
                        style="background: #f8fafc; border-bottom: 1px solid #e2e8f0; font-weight: bold; text-align: center;">
                        SUMMARY</div>
                    <div class="summary-row">
                        <span class="summary-label">Total Entries:</span>
                        <span class="summary-val">{{ count($stockIns) }}</span>
                    </div>
                    <div class="summary-row total-highlight">
                        <span class="summary-label">Total Cost:</span>
                        <span class="summary-val">{{ number_format($stockIns->sum('total_cost'), 2) }} FRW</span>
                    </div>
                </div>
            </td>
        </tr>
    </table>
@endsection